config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions
  resources :posts
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :image, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
   has_many :posts
   validates :firstname, presence: true, length: {maximum: 40}
   validates :lastname, presence: true, length: {maximum: 40}
   validates :email, presence: true, length: {maximum: 200},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
   before_validation { email.downcase! }
   has_secure_password
   validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end
  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end
    def post_params
      params.require(:post).permit(:image, :content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to posts_path(user.id)
      else
        flash.now[:danger] = 'Login failed'
        render 'new'
      end
    end
    def destroy
      session.delete(:user_id)
      flash[:notice] = 'You logged out'
      redirect_to new_session_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :mobilephone, :email, :password, :birthday, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
      end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appfacebookclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>
  <body style="background-color:#e9ebee">
  </style>
  <nav class="navbar navbar-light" style="background-color:#3b5998">
  <p class="navbar-brand" style="color:white"> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp facebook</p>
  <form class="form-inline">
  <% if logged_in? %>
  <button class="btn btn-outline-success" type="submit"><%= link_to "Profile", user_path(current_user.id) %></button>
    <button class="btn btn-outline-success" type="submit"><%= link_to "Logout", session_path(current_user.id), method: :delete %></button>
    <% else %>
    <button class="btn btn-outline-success" type="submit"><%= link_to "Sign up", new_user_path %></button>
    <button class="btn btn-outline-success" type="submit"><%= link_to "Login", new_session_path %></button>
    <% end %>
    </form>
</nav>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
    <br><br><br><br><br>
  <center>
  <nav class="navbar navbar-light bg-light fixed-bottom" style="width:100%; text-align:center; background:white">
    <a class="navbar-brand" href="#" >&copy copyright DIC Student from Rwanda designed by benie</a>
  </nav></center>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="text-center" >
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class:'btn btn-success' %> |
<%= link_to 'Back', posts_path, class:'btn btn-info'%>
</div>

app/views/posts/index.html.erb
<head>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="card text-center">
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
        <% if post.image_url %>
           <%= image_tag post.image_url, style:"width:100px;height:100px;" %>
        <% end %>
        </td>
        <td><%= post.content %></td>
        <td><%= post.user.firstname %></td>
        
        <td><%= link_to 'Show', post, class:'btn btn-success' %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class:'btn btn-info' %></td>
        <td><%= link_to 'Destroy',post, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<div class="text-center">
<%= link_to 'New Post', new_post_path, class: 'btn btn-info ' %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

app/views/posts/new.html.erb
<div class="text-center" >
<h1>New Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path, class:'btn btn-info'%>
</div>

app/views/posts/show.html.erb
<div class="text-center" >
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @post.image.url, style:'height:400px;widht:300px;' %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.firstname %>
</p>

<%= link_to 'Edit', edit_post_path(@post),class:'btn btn-info' %> |
<%= link_to 'Back', posts_path, class:'btn btn-success' %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    <%= form.text_field :firstname,placeholder:'Firstname',class:'field' %>

    <%= form.text_field :lastname ,placeholder:'Lastname',class:'field'%>
  
    <%= form.text_field :mobilephone,placeholder:'Mobile number',class:'field' %>
 
    <%= form.text_field :email,placeholder:'Email',class:'field' %>
  
    <%= form.password_field :password ,placeholder:'Password',class:'field'%>
  
    <br>Birthday<br>
    <%= form.date_select :birthday,placeholder:'Birthday',class:'field' %>
 
    <%= form.text_field :gender,placeholder:'Gender',class:'field' %>
  
  <div class="actions">
    <%= form.submit  %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="text-center" >
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user, class:'btn btn-info' %> |
<%= link_to 'Back', users_path, class:'btn btn-success' %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Mobilephone</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Birthday</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.mobilephone %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.birthday %></td>
        <td><%= user.gender %></td>
        <td><%= link_to 'Show', user, class:'btn btn-info'%></td>
        <td><%= link_to 'Edit', edit_user_path(user), class:'btn btn-success' %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New User', new_user_path, class:'btn btn-info' %>

app/views/users/new.html.erb
<div class="main">
<h1>Create a New Account</h1>
It’s quick and easy.

<%= render 'form', user: @user %>
</div>

 

app/views/users/show.html.erb
<div class="text-center" >
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Mobilephone:</strong>
  <%= @user.mobilephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class:'btn btn-info'%> |
<%= link_to 'Back', posts_path, class:'btn btn-success'%>
</div>